services:
  web:
    build: .
    image: cdcwaiv:web
    env_file:
      - .env.docker
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    command: >
      gunicorn cdcwaiv.wsgi:application
      --bind 0.0.0.0:8000 --workers 2 --timeout 60
    healthcheck:
      test: ["CMD", "sh", "-c", "timeout 2 bash -c '</dev/tcp/127.0.0.1/8000' >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro        # <— place your PEM files here
      - staticfiles:/static:ro
      - mediafiles:/media:ro
    restart: unless-stopped

volumes:
  staticfiles:
  mediafiles:
