services:
  web:
    build: .
    image: cdcwaiv:web
    env_file:
      - .env.docker
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    # If you want logs right away and auto-restart:
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/static:ro   # Nginx serves /static from here
      - mediafiles:/media:ro     # and /media from here
    restart: unless-stopped

volumes:
  staticfiles:
  mediafiles:
