# Generated by Django 5.2 on 2025-04-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case_status_info',
            fields=[
                ('case_status_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('case_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='student_personal_info',
            fields=[
                ('csulb_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('participant_id', models.IntegerField(max_length=15, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('employ_goal', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('enrollment_date', models.DateField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('case_manager', models.CharField(max_length=100)),
                ('intake_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='dor_counselor',
            fields=[
                ('dor_counselor_id', models.AutoField(primary_key=True, serialize=False)),
                ('dor_counselor_name', models.CharField(max_length=100)),
                ('dor_counselor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='waiv_service_info',
            fields=[
                ('service_type', models.IntegerField(primary_key=True, serialize=False)),
                ('service_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='waiv_staff_info',
            fields=[
                ('waiv_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('waiv_staff_name', models.CharField(max_length=100)),
                ('waiv_staff_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='disabilityInfo',
            fields=[
                ('csub_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='waivapp.student_personal_info')),
                ('disabilityType', models.CharField(max_length=100)),
                ('disabilityDetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='studentDoc',
            fields=[
                ('csub_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='waivapp.student_personal_info')),
                ('doc_name', models.CharField(max_length=255)),
                ('received_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='monthly_client_listing_log',
            fields=[
                ('participant_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fund_begin_date', models.DateField()),
                ('fund_end_date', models.DateField()),
                ('district', models.CharField(max_length=100)),
                ('updated_date', models.DateField()),
                ('case_status_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waivapp.case_status_info')),
                ('dor_counselor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waivapp.dor_counselor')),
            ],
        ),
        migrations.CreateModel(
            name='student_academic_log',
            fields=[
                ('academic_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_plan', models.CharField(max_length=100)),
                ('academic_level', models.CharField(max_length=50)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('updated_date', models.DateField()),
                ('csub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waivapp.student_personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='studentLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated', models.DateField()),
                ('case_status_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waivapp.case_status_info')),
                ('csub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waivapp.student_personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='counselingLog',
            fields=[
                ('counsel_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_checkin', models.DateField()),
                ('case_note', models.TextField()),
                ('csub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waivapp.student_personal_info')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waivapp.waiv_service_info')),
                ('waiv_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waivapp.waiv_staff_info')),
            ],
        ),
    ]
