# Generated by Django 5.2 on 2025-04-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waivstaffinfo',
            name='waiv_staff_position',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
