# Generated by Django 5.0.14 on 2025-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
