# Generated by Django 5.0.14 on 2025-05-19 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyclientlistinglog',
            name='dor_counselor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyclientlistinglog',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DorCounselor',
        ),
    ]
