# Generated by Django 5.0.14 on 2025-05-05 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselinglog',
            name='csulb_id',
            field=models.ForeignKey(blank=True, db_column='csulb_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='waivapp.studentpersonalinfo'),
        ),
        migrations.AlterField(
            model_name='studentacademiclog',
            name='csulb_id',
            field=models.ForeignKey(db_column='csulb_id', on_delete=django.db.models.deletion.CASCADE, to='waivapp.studentpersonalinfo'),
        ),
        migrations.AlterField(
            model_name='studentdoc',
            name='csulb_id',
            field=models.OneToOneField(db_column='csulb_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doc', serialize=False, to='waivapp.studentpersonalinfo'),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='csulb_id',
            field=models.ForeignKey(db_column='csulb_id', on_delete=django.db.models.deletion.CASCADE, to='waivapp.studentpersonalinfo'),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='csulb_id',
            field=models.CharField(db_column='csulb_id', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='participant_id',
            field=models.CharField(db_column='participant_id', max_length=15, unique=True),
        ),
    ]
