# Generated by Django 5.0.14 on 2025-06-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0002_alter_studentpersonalinfo_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinfo',
            name='job_placement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
