# Generated by Django 5.2 on 2025-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0002_waivstaffinfo_waiv_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyclientlistinglog',
            name='fund_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
