# Generated by Django 5.0.14 on 2025-05-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0002_alter_counselinglog_csulb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyclientlistinglog',
            name='participant_id',
            field=models.CharField(db_column='participant_id', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
