# Generated by Django 5.0.14 on 2025-05-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0002_alter_monthlyclientlistinglog_dor_counselor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyclientlistinglog',
            name='fund_begin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
