# Generated by Django 5.0.14 on 2025-05-05 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0003_alter_monthlyclientlistinglog_participant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waivuser',
            name='position',
            field=models.CharField(choices=[('counselor', 'Counselor'), ('case_manager', 'Case Manager')], default='counselor', max_length=30),
        ),
        migrations.CreateModel(
            name='CaseManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaivCounselor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
