# Generated by Django 5.0.14 on 2025-05-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0003_alter_monthlyclientlistinglog_fund_begin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademiclog',
            name='csulb_id',
            field=models.OneToOneField(db_column='csulb_id', on_delete=django.db.models.deletion.CASCADE, related_name='academic_log', to='waivapp.studentpersonalinfo'),
        ),
    ]
