# Generated by Django 5.0.14 on 2025-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0004_alter_waivuser_position_casemanager_waivcounselor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waivuser',
            name='position',
            field=models.CharField(choices=[('counselor', 'Counselor'), ('case_manager', 'Case Manager'), ('admin', 'Administrator')], default='counselor', max_length=30),
        ),
    ]
