# Generated by Django 5.0.14 on 2025-06-03 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0004_alter_studentacademiclog_csulb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinSimplicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checkin', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('imported_date', models.DateField(auto_now_add=True)),
                ('csulb_id', models.ForeignKey(db_column='csulb_id', on_delete=django.db.models.deletion.CASCADE, to='waivapp.studentpersonalinfo')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_counselor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
