# Generated by Django 5.0.14 on 2025-05-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0005_alter_waivuser_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waivcounselor',
            old_name='address',
            new_name='position',
        ),
        migrations.AddField(
            model_name='casemanager',
            name='position',
            field=models.TextField(default='case_manager'),
            preserve_default=False,
        ),
    ]
