# Generated by Django 5.0.14 on 2025-06-03 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0005_checkinsimplicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinsimplicity',
            name='csulb_id',
            field=models.CharField(help_text='Raw Participant_ID from Simplicity (no FK lookup).', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkinsimplicity',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_counselor', to=settings.AUTH_USER_MODEL),
        ),
    ]
