# Generated by Django 5.0.14 on 2025-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0006_rename_address_waivcounselor_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waivcounselor',
            name='admin',
        ),
        migrations.AlterField(
            model_name='waivuser',
            name='position',
            field=models.CharField(choices=[('counselor', 'Counselor'), ('case_manager', 'Case Manager')], default='counselor', max_length=30),
        ),
        migrations.DeleteModel(
            name='CaseManager',
        ),
        migrations.DeleteModel(
            name='WaivCounselor',
        ),
    ]
