# Generated by Django 5.0.14 on 2025-05-14 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0007_remove_waivcounselor_admin_alter_waivuser_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlog',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='studentlog',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counselinglog',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentacademiclog',
            name='academic_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
