# Generated by Django 5.0.14 on 2025-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0008_remove_studentlog_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyclientlistinglog',
            name='updated_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
