# Generated by Django 5.0.14 on 2025-05-14 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0009_alter_monthlyclientlistinglog_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdoc',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
