# Generated by Django 5.0.14 on 2025-05-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivapp', '0010_studentdoc_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdoc',
            name='doc_types',
        ),
        migrations.RemoveField(
            model_name='studentdoc',
            name='file',
        ),
        migrations.AddField(
            model_name='studentdoc',
            name='doc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
